id: P003145
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W22354
  title: རྗེ་ཤིང་བཟའ་པཎྜི་ཏ་སྐུ་འཕྲེང་ལྔ་པ་སྐལ་བཟང་ཆོས་ཀྱི་རྒྱལ་མཚན་གྱི་རྣམ་ཐར
  author: ''
  volumes:
    ac9fc2cb336f468c8252f76aa88ec387:
      image_group_id: I1GS55163
      title: ''
      volume_number: 1
      total_pages: 149
      base_file: v001.txt
