id: ID6626A2D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T15:15:54+00:00'
last_modified: '2022-06-07T17:53:49.969557+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W22354
  title: རྗེ་ཤིང་བཟའ་པཎྜི་ཏ་སྐུ་འཕྲེང་ལྔ་པ་སྐལ་བཟང་ཆོས་ཀྱི་རྒྱལ་མཚན་གྱི་རྣམ་ཐར
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '6666':
      image_group_id: I1GS55163
      title: ''
      total_pages: 149
      order: 1
      base_file: 6666.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
